#!/bin/bash
swift main.swift '('
swift main.swift '(())' 
swift main.swift '()()'
swift main.swift '(((' 
swift main.swift '(()(()('
swift main.swift '))((((('
swift main.swift '())'
swift main.swift '))('
swift main.swift ')))'
swift main.swift ')())())'
