#!/bin/bash
lua main.lua '('
lua main.lua '(())' 
lua main.lua '()()'
lua main.lua '(((' 
lua main.lua '(()(()('
lua main.lua '))((((('
lua main.lua '())'
lua main.lua '))('
lua main.lua ')))'
lua main.lua ')())())'
